- name: Unarchive a file that is already on the remote machine  
  unarchive:  
    src: artifact.tar.gz
    dest: ~/project
    remote_src: yes
- name: "start the server"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start