- name: Creates directory # this added because of that error
# dest '/home/ubuntu/project' must be an existing dir"
  file:
    path: ~/project/web
    state: directory
- name: Unarchive a file that is already on the remote machine  
  unarchive:  
    src: ~/project/backend/artifact.tar.gz
    dest: ~/project/web
    remote_src: yes
- name: "start the server"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start